### PR TITLE
Add replaceConf. Update go-ipfs and node-ipfs-api package versions.

### PR DESCRIPTION
**Pull request by haadcode**

### CODE REVIEW

**Comment by haadcode** [comment]
If/when you merge this, could you also update the packages in npm so that the new version get pulled accordingly? Thanks.

**Comment by jbenet** [comment]
Seems useful to me. @diasdavid ?

**Comment by diasdavid** [comment]
sgtm :+1:

**Comment by diasdavid** [comment]
@haadcode released and published a new version
https://github.com/ipfs/node-ipfsd-ctl/releases/tag/v0.5.0

**Comment by haadcode** [comment]
Cheers ya'll!

**Pull request merged**
